name: LIFT
  
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - _libgcc_mutex==0.1=conda_forge
  - _openmp_mutex==4.5=2_kmp_llvm
  - _py-xgboost-mutex==2.0=gpu_0
  - blas-devel==3.9.0=16_linux64_mkl
  - blas==2.116=mkl
  - brotli-bin==1.1.0=hb9d3cd8_2
  - brotli-python==1.1.0=py39hf88036b_2
  - brotli==1.1.0=hb9d3cd8_2
  - bzip2==1.0.8=h4bc722e_7
  - ca-certificates==2025.10.5
  - cairo==1.18.0=h3faef2a_0
  - certifi==2025.10.5
  - cffi==1.17.1=py39h15c3d72_0
  - charset-normalizer==3.4.0=pyhd8ed1ab_1
  - contourpy==1.2.1=py39h7633fee_0
  - cuda-cudart==12.1.105=0
  - cuda-cupti==12.1.105=0
  - cuda-libraries==12.1.0=0
  - cuda-nvrtc==12.1.105=0
  - cuda-nvtx==12.1.105=0
  - cuda-opencl==12.6.77=0
  - cuda-runtime==12.1.0=0
  - cuda-version==12.6=3
  - cycler==0.12.1=pyhd8ed1ab_1
  - et_xmlfile==2.0.0=pyhd8ed1ab_1
  - expat==2.6.4=h5888daf_0
  - ffmpeg==4.3=hf484d3e_0
  - filelock==3.16.1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono==2.37=hab24e00_0
  - font-ttf-inconsolata==3.000=h77eed37_0
  - font-ttf-source-code-pro==2.038=h77eed37_0
  - font-ttf-ubuntu==0.83=h77eed37_3
  - fontconfig==2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem==1=0
  - fonts-conda-forge==1=0
  - fonttools==4.55.3=py39h9399b63_1
  - freetype==2.12.1=h267a509_2
  - gmp==6.3.0=hac33072_2
  - gmpy2==2.1.5=py39h7196dd7_3
  - gnutls==3.6.13=h85f3911_1
  - greenlet==3.1.1=py39hf88036b_1
  - h2==4.1.0=pyhd8ed1ab_1
  - hpack==4.0.0=pyhd8ed1ab_1
  - hyperframe==6.0.1=pyhd8ed1ab_1
  - icu==73.2=h59595ed_0
  - idna==3.10=pyhd8ed1ab_1
  - importlib-resources==6.4.5=pyhd8ed1ab_1
  - importlib_resources==6.4.5=pyhd8ed1ab_1
  - jinja2==3.1.5=pyhd8ed1ab_0
  - joblib==1.4.2=pyhd8ed1ab_1
  - jpeg==9e=h166bdaf_2
  - keyutils==1.6.1=h166bdaf_0
  - kiwisolver==1.4.7=py39h74842e3_0
  - krb5==1.21.3=h659f571_0
  - lame==3.100=h166bdaf_1003
  - lcms2==2.12=hddcbb42_0
  - ld_impl_linux-64==2.43=h712a8e2_2
  - lerc==4.0.0=h27087fc_0
  - libblas==3.9.0=16_linux64_mkl
  - libboost-python==1.84.0=py39hf59e57a_7
  - libboost==1.84.0=hba137d9_3
  - libbrotlicommon==1.1.0=hb9d3cd8_2
  - libbrotlidec==1.1.0=hb9d3cd8_2
  - libbrotlienc==1.1.0=hb9d3cd8_2
  - libcblas==3.9.0=16_linux64_mkl
  - libcublas==12.1.0.26=0
  - libcufft==11.0.2.4=0
  - libcufile==1.11.1.6=0
  - libcurand==10.3.7.77=0
  - libcusolver==11.4.4.55=0
  - libcusparse==12.0.2.55=0
  - libdeflate==1.17=h0b41bf4_0
  - libedit==3.1.20191231=he28a2e2_2
  - libexpat==2.6.4=h5888daf_0
  - libffi==3.4.2=h7f98852_5
  - libgcc-ng==14.2.0=h69a702a_1
  - libgcc==14.2.0=h77fa898_1
  - libgfortran-ng==14.2.0=h69a702a_1
  - libgfortran5==14.2.0=hd5240d6_1
  - libgfortran==14.2.0=h69a702a_1
  - libglib==2.80.2=hf974151_0
  - libgomp==14.2.0=h77fa898_1
  - libhwloc==2.11.2=default_he43201b_1000
  - libiconv==1.17=hd590300_2
  - libjpeg-turbo==2.0.0=h9bf148f_0
  - liblapack==3.9.0=16_linux64_mkl
  - liblapacke==3.9.0=16_linux64_mkl
  - liblightgbm==4.5.0=cuda_hd1e9f75_3
  - liblzma-devel==5.6.3=hb9d3cd8_1
  - liblzma==5.6.3=hb9d3cd8_1
  - libnpp==12.0.2.50=0
  - libnsl==2.0.1=hd590300_0
  - libnvjitlink==12.1.105=0
  - libnvjpeg==12.1.1.14=0
  - libpng==1.6.43=h2797004_0
  - libpq==16.6=h035377e_1
  - librdkit==2024.03.6=h04b5189_0
  - libsqlite==3.46.0=hde9e2c9_0
  - libstdcxx-ng==14.2.0=h4852527_1
  - libstdcxx==14.2.0=hc0a3c3a_1
  - libtiff==4.2.0=hf544144_3
  - libuuid==2.38.1=h0b41bf4_0
  - libwebp-base==1.5.0=h851e524_0
  - libxcb==1.15=h0b41bf4_0
  - libxcrypt==4.4.36=hd590300_1
  - libxgboost==2.1.3=cuda126_hf02754f_0
  - libxml2==2.12.7=hc051c1a_1
  - libzlib==1.2.13=h4ab18f5_6
  - lightgbm==4.5.0=cuda_py_3
  - llvm-openmp==15.0.7=h0cdce71_0
  - markupsafe==3.0.2=py39h9399b63_1
  - matplotlib-base==3.8.4=py39h10d1fc8_2
  - mkl-devel==2022.1.0=ha770c72_916
  - mkl-include==2022.1.0=h84fe81f_915
  - mkl==2022.1.0=h84fe81f_915
  - mordred==1.2.0=py_1
  - mpc==1.3.1=h24ddda3_1
  - mpfr==4.2.1=h90cbb55_3
  - mpmath==1.3.0=pyhd8ed1ab_1
  - munkres==1.1.4=pyh9f0ad1d_0
  - nccl==2.24.3.1=hb92ee24_0
  - ncurses==6.5=he02047a_1
  - nettle==3.6=he412f7d_0
  - networkx==3.2.1=pyhd8ed1ab_0
  - olefile==0.47=pyhd8ed1ab_1
  - openh264==2.1.1=h780b84a_0
  - openjpeg==2.4.0=hb52868f_1
  - openpyxl==3.1.5=py39h79730dd_1
  - openssl==3.5.4
  - packaging==24.2=pyhd8ed1ab_2
  - pcre2==10.43=hcad00b1_0
  - pillow==8.2.0=py39hf95b381_1
  - pip==24.3.1=pyh8b19718_2
  - pixman==0.44.2=h29eaf8c_0
  - platformdirs==4.3.6=pyhd8ed1ab_1
  - pooch==1.8.2=pyhd8ed1ab_1
  - pthread-stubs==0.4=hb9d3cd8_1002
  - py-xgboost==2.1.3=cuda126_pyh206be00_0
  - pycairo==1.27.0=py39h92ccb2d_0
  - pycparser==2.22=pyh29332c3_1
  - pyparsing==3.2.0=pyhd8ed1ab_2
  - pysocks==1.7.1=pyha55dd90_7
  - python-dateutil==2.9.0.post0=pyhff2d567_1
  - python-tzdata==2024.2=pyhd8ed1ab_1
  - python==3.9.19=h0755675_0_cpython
  - python_abi==3.9=5_cp39
  - pytorch-cuda==12.1=ha16c6d3_6
  - pytorch-mutex==1.0=cuda
  - pytorch==2.1.0=py3.9_cuda12.1_cudnn8.9.2_0
  - pytz==2024.1=pyhd8ed1ab_0
  - pyyaml==6.0.2=py39h8cd3c5a_1
  - qhull==2020.2=h434a139_5
  - rdkit==2024.03.6=py39h649241c_0
  - readline==8.2=h8228510_1
  - reportlab==3.5.68=py39he59360d_1
  - requests==2.32.3=pyhd8ed1ab_1
  - scikit-learn==1.6.0=py39h4b7350c_0
  - scipy==1.11.2=py39h6183b62_0
  - setuptools==75.6.0=pyhff2d567_1
  - six==1.17.0=pyhd8ed1ab_0
  - skunk==1.3.0=pyh29332c3_0
  - sqlalchemy==2.0.36=py39h8cd3c5a_0
  - sympy==1.13.3=pypyh2585a3b_103
  - tbb==2021.13.0=hceb3a55_1
  - threadpoolctl==3.5.0=pyhc1e730c_0
  - tk==8.6.13=noxft_h4845f30_101
  - torchaudio==2.1.0=py39_cu121
  - torchtriton==2.1.0=py39
  - torchvision==0.16.0=py39_cu121
  - tqdm==4.67.1=py39h2f386ee_0
  - typing-extensions==4.12.2=hd8ed1ab_1
  - typing_extensions==4.12.2=pyha770c72_1
  - tzdata==2024b=hc8b5060_0
  - unicodedata2==15.1.0=py39h8cd3c5a_1
  - urllib3==2.3.0=pyhd8ed1ab_0
  - wheel==0.45.1=pyhd8ed1ab_1
  - xgboost==2.1.3=cuda126_pyh993ee4f_0
  - xorg-kbproto==1.0.7=hb9d3cd8_1003
  - xorg-libice==1.1.2=hb9d3cd8_0
  - xorg-libsm==1.2.5=he73a12e_0
  - xorg-libx11==1.8.9=h8ee46fc_0
  - xorg-libxau==1.0.12=hb9d3cd8_0
  - xorg-libxdmcp==1.1.5=hb9d3cd8_0
  - xorg-libxext==1.3.4=h0b41bf4_2
  - xorg-libxrender==0.9.11=hd590300_0
  - xorg-renderproto==0.11.1=hb9d3cd8_1003
  - xorg-xextproto==7.3.0=hb9d3cd8_1004
  - xorg-xproto==7.0.31=hb9d3cd8_1008
  - xz-gpl-tools==5.6.3=hbcc6ac9_1
  - xz-tools==5.6.3=hb9d3cd8_1
  - xz==5.6.3=hbcc6ac9_1
  - yaml==0.2.5=h7f98852_2
  - zipp==3.21.0=pyhd8ed1ab_1
  - zlib==1.2.13=h4ab18f5_6
  - zstandard==0.23.0=py39h08a7858_1
  - zstd==1.5.6=ha6fb4c9_0
  - transformers
  - python-levenshtein
  - tensorboard